version: "2.0"
services:
  app1:
    build: ./src
    container_name: chat_app1
    ports:
      - "1234:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
    networks:
      - chatnet

  app2:
    build: ./src
    container_name: chat_app2
    ports:
      - "5678:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
    networks:
      - chatnet

  redis:
    image: redis:latest
    container_name: chat_redis
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
